/**
 * Mock data for the Events page.
 *
 * Phase 5 split — extracted from EventsPage.tsx. Pure data.
 */

import type { Attendee, Conference, Registration } from './_types';

export const mockConferences: Conference[] = [
  {
    id: '1',
    title: 'Global Islamic Finance Summit 2025',
    organizer: 'Islamic Development Bank',
    description: 'Join industry leaders in discussing the future of Islamic finance, halal economy, and ethical investments. This premier event brings together policymakers, scholars, and business leaders from across the globe.',
    format: 'In-Person',
    category: 'Business & Economics',
    startDate: '2025-04-15',
    endDate: '2025-04-17',
    location: 'Dubai, UAE',
    capacity: 500,
    registered: 380,
    price: 5000,
    featured: true,
    bannerGradient: 'linear-gradient(135deg, #6B46C1 0%, #9333EA 100%)',
    topics: ['Islamic Banking', 'Halal Economy', 'Sukuk Markets', 'ESG Investing', 'Takaful Insurance'],
    venue: {
      name: 'Dubai International Convention Centre',
      address: 'Sheikh Zayed Road, Trade Centre 2, Dubai, UAE',
      amenities: ['Free Parking', 'WiFi Available', 'Wheelchair Access', 'Prayer Rooms', 'Halal Catering'],
    },
    tickets: [
      { tier: 'Standard', price: 5000, benefits: ['General access to all sessions', 'Lunch & refreshments', 'Digital certificate'] },
      { tier: 'VIP', price: 12000, benefits: ['All Standard benefits', 'Priority seating', 'Networking dinner', 'Swag bag', '1-on-1 meeting slots'], popular: true },
      { tier: 'Premium', price: 25000, benefits: ['All VIP benefits', 'Workshop access', 'Speaker meet & greet', 'Lifetime recordings', 'Executive lounge access'] },
    ],
    speakers: [
      { name: 'Dr. Ahmed Al-Farsi', title: 'Chief Economist', company: 'Islamic Development Bank', avatarColor: '#D4A853', expertise: ['Islamic Economics', 'Policy'] },
      { name: 'Fatima Hassan', title: 'CEO', company: 'Dubai Islamic Bank', avatarColor: '#D4A853', expertise: ['Banking', 'Leadership'] },
      { name: 'Prof. Yusuf Rahman', title: 'Scholar', company: 'Al-Azhar University', avatarColor: '#10B981', expertise: ['Shariah', 'Finance'] },
      { name: 'Sarah Abdullah', title: 'Director', company: 'World Bank', avatarColor: '#F59E0B', expertise: ['Development', 'ESG'] },
    ],
    schedule: [
      {
        day: 1,
        sessions: [
          { time: '09:00 - 09:30', title: 'Opening Ceremony', type: 'ceremony' },
          { time: '09:30 - 10:30', title: 'Keynote: Future of Islamic Finance', type: 'keynote' },
          { time: '11:00 - 12:00', title: 'Panel Discussion: Halal Economy', type: 'panel' },
          { time: '12:00 - 13:00', title: 'Networking Lunch', type: 'networking' },
          { time: '13:00 - 15:00', title: 'Workshop A: Sukuk Structuring', type: 'workshop' },
          { time: '15:00 - 16:30', title: 'Exhibition Tour', type: 'exhibition' },
        ],
      },
      {
        day: 2,
        sessions: [
          { time: '09:00 - 10:00', title: 'Morning Keynote: ESG & Islamic Finance', type: 'keynote' },
          { time: '10:30 - 11:30', title: 'Industry Panel: Digital Transformation', type: 'panel' },
          { time: '11:30 - 13:00', title: 'Workshop B: Takaful Innovation', type: 'workshop' },
          { time: '14:00 - 15:00', title: 'Closing Ceremony', type: 'ceremony' },
        ],
      },
    ],
  },
  {
    id: '2',
    title: 'TechConnect Innovation Forum',
    organizer: 'Global Tech Alliance',
    description: 'Explore cutting-edge technologies including AI, blockchain, IoT, and cloud computing. Network with innovators, investors, and tech leaders shaping the digital future.',
    format: 'Virtual',
    category: 'Technology',
    startDate: '2025-05-10',
    endDate: '2025-05-12',
    location: 'Virtual Event',
    capacity: 1000,
    registered: 750,
    price: 3000,
    featured: false,
    bannerGradient: 'linear-gradient(135deg, #0891B2 0%, #D4A853 100%)',
    topics: ['Artificial Intelligence', 'Blockchain', 'IoT', 'Cloud Computing', 'Cybersecurity'],
    venue: {
      name: 'Virtual Platform (Zoom)',
      address: 'Online',
      amenities: ['HD Streaming', 'Interactive Q&A', 'Breakout Rooms', 'Recording Access'],
    },
    tickets: [
      { tier: 'Standard', price: 3000, benefits: ['Access to all sessions', 'Digital materials', 'Certificate'] },
      { tier: 'VIP', price: 8000, benefits: ['All Standard benefits', 'Virtual networking', 'Workshop access', 'Lifetime recordings'], popular: true },
      { tier: 'Premium', price: 15000, benefits: ['All VIP benefits', 'Speaker Q&A', '1-on-1 mentorship', 'Premium support'] },
    ],
    speakers: [
      { name: 'Dr. Lisa Chen', title: 'AI Research Lead', company: 'Google', avatarColor: '#EC4899', expertise: ['AI', 'Machine Learning'] },
      { name: 'Marcus Johnson', title: 'CTO', company: 'Microsoft Azure', avatarColor: '#8B5CF6', expertise: ['Cloud', 'DevOps'] },
      { name: 'Aisha Patel', title: 'Blockchain Architect', company: 'Ethereum Foundation', avatarColor: '#10B981', expertise: ['Blockchain', 'Web3'] },
      { name: 'Robert Kim', title: 'Security Director', company: 'Cisco', avatarColor: '#F59E0B', expertise: ['Cybersecurity', 'IoT'] },
    ],
    schedule: [
      {
        day: 1,
        sessions: [
          { time: '09:00 - 09:30', title: 'Virtual Opening', type: 'ceremony' },
          { time: '09:30 - 10:30', title: 'Keynote: AI Revolution', type: 'keynote' },
          { time: '11:00 - 12:00', title: 'Panel: Future of Blockchain', type: 'panel' },
          { time: '12:00 - 13:00', title: 'Virtual Networking', type: 'networking' },
          { time: '13:00 - 15:00', title: 'Workshop: Building with AI', type: 'workshop' },
          { time: '15:00 - 16:30', title: 'Tech Demo Showcase', type: 'exhibition' },
        ],
      },
      {
        day: 2,
        sessions: [
          { time: '09:00 - 10:00', title: 'Cloud Computing Keynote', type: 'keynote' },
          { time: '10:30 - 11:30', title: 'Cybersecurity Panel', type: 'panel' },
          { time: '11:30 - 13:00', title: 'IoT Workshop', type: 'workshop' },
          { time: '14:00 - 15:00', title: 'Closing & Awards', type: 'ceremony' },
        ],
      },
    ],
  },
  {
    id: '3',
    title: 'Healthcare Leadership Conference',
    organizer: 'World Health Forum',
    description: 'A gathering of healthcare professionals, policymakers, and innovators to discuss the future of healthcare delivery, medical technology, and patient care excellence.',
    format: 'Hybrid',
    category: 'Healthcare',
    startDate: '2025-06-20',
    endDate: '2025-06-22',
    location: 'London, UK',
    capacity: 300,
    registered: 220,
    price: 7000,
    featured: false,
    bannerGradient: 'linear-gradient(135deg, #059669 0%, #10B981 100%)',
    topics: ['Digital Health', 'Patient Care', 'Medical Innovation', 'Healthcare Policy', 'Telemedicine'],
    venue: {
      name: 'London ExCeL Centre',
      address: 'Royal Victoria Dock, London E16 1XL, UK',
      amenities: ['Parking Available', 'WiFi', 'Accessibility', 'Medical Facilities', 'Hybrid Setup'],
    },
    tickets: [
      { tier: 'Standard', price: 7000, benefits: ['Conference access', 'Meals included', 'Certificate'] },
      { tier: 'VIP', price: 15000, benefits: ['All Standard benefits', 'VIP lounge', 'Networking events', 'Speaker access'], popular: true },
      { tier: 'Premium', price: 30000, benefits: ['All VIP benefits', 'CME credits', 'Premium workshops', 'Executive dinner'] },
    ],
    speakers: [
      { name: 'Dr. Emily Watson', title: 'Chief Medical Officer', company: 'NHS', avatarColor: '#D4A853', expertise: ['Healthcare Policy', 'Leadership'] },
      { name: 'Prof. James Lee', title: 'Surgeon', company: 'Mayo Clinic', avatarColor: '#D4A853', expertise: ['Surgery', 'Innovation'] },
      { name: 'Dr. Amina Javed', title: 'Director', company: 'WHO', avatarColor: '#EC4899', expertise: ['Public Health', 'Global Health'] },
      { name: 'Michael Brown', title: 'CEO', company: 'HealthTech Inc', avatarColor: '#10B981', expertise: ['Digital Health', 'AI'] },
    ],
    schedule: [
      {
        day: 1,
        sessions: [
          { time: '09:00 - 09:30', title: 'Opening Ceremony', type: 'ceremony' },
          { time: '09:30 - 10:30', title: 'Keynote: Future of Healthcare', type: 'keynote' },
          { time: '11:00 - 12:00', title: 'Panel: Digital Transformation', type: 'panel' },
          { time: '12:00 - 13:00', title: 'Lunch & Networking', type: 'networking' },
          { time: '13:00 - 15:00', title: 'Workshop: Telemedicine Best Practices', type: 'workshop' },
          { time: '15:00 - 16:30', title: 'Medical Device Exhibition', type: 'exhibition' },
        ],
      },
      {
        day: 2,
        sessions: [
          { time: '09:00 - 10:00', title: 'Patient Care Excellence Keynote', type: 'keynote' },
          { time: '10:30 - 11:30', title: 'Healthcare Policy Panel', type: 'panel' },
          { time: '11:30 - 13:00', title: 'Clinical Innovation Workshop', type: 'workshop' },
          { time: '14:00 - 15:00', title: 'Closing Ceremony', type: 'ceremony' },
        ],
      },
    ],
  },
  {
    id: '4',
    title: 'Education Technology Expo',
    organizer: 'EdTech Global Network',
    description: 'Discover the latest innovations in educational technology, from AI-powered learning to virtual classrooms. Connect with educators, developers, and investors.',
    format: 'In-Person',
    category: 'Education',
    startDate: '2025-07-08',
    endDate: '2025-07-10',
    location: 'Toronto, Canada',
    capacity: 400,
    registered: 350,
    price: 4500,
    featured: false,
    bannerGradient: 'linear-gradient(135deg, #DC2626 0%, #EF4444 100%)',
    topics: ['AI in Education', 'Virtual Classrooms', 'Learning Management', 'EdTech Startups', 'Gamification'],
    venue: {
      name: 'Metro Toronto Convention Centre',
      address: '255 Front St W, Toronto, ON M5V 2W6, Canada',
      amenities: ['Free Parking', 'WiFi', 'Accessibility', 'Cafeteria', 'Demo Labs'],
    },
    tickets: [
      { tier: 'Standard', price: 4500, benefits: ['Expo access', 'Demo sessions', 'Certificate'] },
      { tier: 'VIP', price: 10000, benefits: ['All Standard benefits', 'Workshop access', 'Networking dinner', 'Exhibitor meetings'], popular: true },
      { tier: 'Premium', price: 20000, benefits: ['All VIP benefits', 'Investor pitch', 'Lifetime access', 'VIP lounge'] },
    ],
    speakers: [
      { name: 'Dr. Sarah Mitchell', title: 'Dean', company: 'MIT Media Lab', avatarColor: '#8B5CF6', expertise: ['EdTech', 'Innovation'] },
      { name: 'David Wong', title: 'Founder', company: 'Coursera', avatarColor: '#F59E0B', expertise: ['Online Learning', 'Startups'] },
      { name: 'Prof. Nadia Ali', title: 'Education Director', company: 'UNESCO', avatarColor: '#10B981', expertise: ['Policy', 'Global Ed'] },
      { name: 'Tom Harris', title: 'CEO', company: 'Khan Academy', avatarColor: '#D4A853', expertise: ['Learning Tech', 'Scale'] },
    ],
    schedule: [
      {
        day: 1,
        sessions: [
          { time: '09:00 - 09:30', title: 'Welcome & Opening', type: 'ceremony' },
          { time: '09:30 - 10:30', title: 'Keynote: AI & Education', type: 'keynote' },
          { time: '11:00 - 12:00', title: 'Panel: Future of Learning', type: 'panel' },
          { time: '12:00 - 13:00', title: 'Networking Lunch', type: 'networking' },
          { time: '13:00 - 15:00', title: 'Workshop: Building EdTech Products', type: 'workshop' },
          { time: '15:00 - 16:30', title: 'Startup Showcase', type: 'exhibition' },
        ],
      },
      {
        day: 2,
        sessions: [
          { time: '09:00 - 10:00', title: 'Virtual Classroom Keynote', type: 'keynote' },
          { time: '10:30 - 11:30', title: 'Gamification Panel', type: 'panel' },
          { time: '11:30 - 13:00', title: 'LMS Workshop', type: 'workshop' },
          { time: '14:00 - 15:00', title: 'Awards & Closing', type: 'ceremony' },
        ],
      },
    ],
  },
  {
    id: '5',
    title: 'Digital Marketing Masterclass',
    organizer: 'Marketing Pro Institute',
    description: 'Master the art of digital marketing with hands-on workshops covering SEO, social media, content strategy, and growth hacking. Learn from industry experts.',
    format: 'Virtual',
    category: 'Marketing',
    startDate: '2025-08-15',
    endDate: '2025-08-17',
    location: 'Virtual Event',
    capacity: 200,
    registered: 180,
    price: 2500,
    featured: false,
    bannerGradient: 'linear-gradient(135deg, #EA580C 0%, #F97316 100%)',
    topics: ['SEO', 'Social Media', 'Content Marketing', 'Growth Hacking', 'Analytics'],
    venue: {
      name: 'Virtual Platform (Google Meet)',
      address: 'Online',
      amenities: ['HD Video', 'Screen Sharing', 'Breakout Sessions', 'Recording Access'],
    },
    tickets: [
      { tier: 'Standard', price: 2500, benefits: ['All sessions', 'Templates & tools', 'Certificate'] },
      { tier: 'VIP', price: 6000, benefits: ['All Standard benefits', '1-on-1 coaching', 'Premium templates', 'Lifetime access'], popular: true },
      { tier: 'Premium', price: 12000, benefits: ['All VIP benefits', 'Agency audit', 'Custom strategy', 'Monthly follow-ups'] },
    ],
    speakers: [
      { name: 'Jessica Martinez', title: 'CMO', company: 'HubSpot', avatarColor: '#EC4899', expertise: ['Content', 'Strategy'] },
      { name: 'Ryan Thompson', title: 'SEO Expert', company: 'Moz', avatarColor: '#D4A853', expertise: ['SEO', 'Analytics'] },
      { name: 'Priya Sharma', title: 'Social Media Director', company: 'Meta', avatarColor: '#10B981', expertise: ['Social', 'Ads'] },
      { name: 'Alex Turner', title: 'Growth Lead', company: 'Shopify', avatarColor: '#F59E0B', expertise: ['Growth', 'Conversion'] },
    ],
    schedule: [
      {
        day: 1,
        sessions: [
          { time: '09:00 - 09:30', title: 'Kickoff Session', type: 'ceremony' },
          { time: '09:30 - 10:30', title: 'Keynote: Marketing Trends 2025', type: 'keynote' },
          { time: '11:00 - 12:00', title: 'Panel: Social Media Strategy', type: 'panel' },
          { time: '12:00 - 13:00', title: 'Virtual Networking', type: 'networking' },
          { time: '13:00 - 15:00', title: 'Workshop: SEO Mastery', type: 'workshop' },
          { time: '15:00 - 16:30', title: 'Tool Demonstrations', type: 'exhibition' },
        ],
      },
      {
        day: 2,
        sessions: [
          { time: '09:00 - 10:00', title: 'Content Marketing Keynote', type: 'keynote' },
          { time: '10:30 - 11:30', title: 'Growth Hacking Panel', type: 'panel' },
          { time: '11:30 - 13:00', title: 'Analytics Workshop', type: 'workshop' },
          { time: '14:00 - 15:00', title: 'Q&A & Closing', type: 'ceremony' },
        ],
      },
    ],
  },
  {
    id: '6',
    title: 'Halal Economy World Congress',
    organizer: 'Global Halal Council',
    description: 'The premier global gathering for halal industry leaders, covering halal food, pharmaceuticals, cosmetics, tourism, and Islamic finance. Network with stakeholders worldwide.',
    format: 'In-Person',
    category: 'Business & Economics',
    startDate: '2025-09-05',
    endDate: '2025-09-07',
    location: 'Kuala Lumpur, Malaysia',
    capacity: 600,
    registered: 420,
    price: 6000,
    featured: false,
    bannerGradient: 'linear-gradient(135deg, #6B46C1 0%, #9333EA 100%)',
    topics: ['Halal Food', 'Halal Tourism', 'Halal Pharma', 'Halal Cosmetics', 'Islamic Finance'],
    venue: {
      name: 'Kuala Lumpur Convention Centre',
      address: 'Jalan Pinang, Kuala Lumpur City Centre, 50088 Kuala Lumpur, Malaysia',
      amenities: ['Free Parking', 'WiFi', 'Prayer Rooms', 'Halal Dining', 'Accessibility'],
    },
    tickets: [
      { tier: 'Standard', price: 6000, benefits: ['Conference access', 'Halal meals', 'Certificate'] },
      { tier: 'VIP', price: 14000, benefits: ['All Standard benefits', 'VIP networking', 'Gala dinner', 'Exhibition booth', 'Meeting slots'], popular: true },
      { tier: 'Premium', price: 28000, benefits: ['All VIP benefits', 'Speaking slot', 'Media coverage', 'Sponsor booth', 'Executive lounge'] },
    ],
    speakers: [
      { name: 'Dato Sri Ahmad Zaki', title: 'Chairman', company: 'JAKIM', avatarColor: '#D4A853', expertise: ['Halal Standards', 'Certification'] },
      { name: 'Siti Nurhaliza', title: 'CEO', company: 'Halal Food Corp', avatarColor: '#10B981', expertise: ['Food Industry', 'Business'] },
      { name: 'Dr. Tariq Mahmood', title: 'Director', company: 'Islamic Chamber of Commerce', avatarColor: '#D4A853', expertise: ['Trade', 'Economics'] },
      { name: 'Amira Khan', title: 'Founder', company: 'Halal Tourism Hub', avatarColor: '#EC4899', expertise: ['Tourism', 'Marketing'] },
    ],
    schedule: [
      {
        day: 1,
        sessions: [
          { time: '09:00 - 09:30', title: 'Opening Ceremony', type: 'ceremony' },
          { time: '09:30 - 10:30', title: 'Keynote: Global Halal Economy', type: 'keynote' },
          { time: '11:00 - 12:00', title: 'Panel: Halal Food Industry', type: 'panel' },
          { time: '12:00 - 13:00', title: 'Halal Lunch & Networking', type: 'networking' },
          { time: '13:00 - 15:00', title: 'Workshop: Halal Certification', type: 'workshop' },
          { time: '15:00 - 16:30', title: 'Halal Expo Tour', type: 'exhibition' },
        ],
      },
      {
        day: 2,
        sessions: [
          { time: '09:00 - 10:00', title: 'Tourism & Travel Keynote', type: 'keynote' },
          { time: '10:30 - 11:30', title: 'Halal Pharma & Cosmetics Panel', type: 'panel' },
          { time: '11:30 - 13:00', title: 'Business Development Workshop', type: 'workshop' },
          { time: '14:00 - 15:00', title: 'Gala Dinner & Awards', type: 'ceremony' },
        ],
      },
    ],
  },
];

export const mockAttendees: Attendee[] = [
  { name: 'Abdullah Rahman', tagline: 'Fintech Innovator', company: 'Dubai Financial Hub', designation: 'CEO', avatarColor: '#D4A853', verified: true, online: true },
  { name: 'Zainab Malik', tagline: 'Islamic Banking Expert', company: 'Maybank Islamic', designation: 'VP Operations', avatarColor: '#D4A853', verified: true, online: false },
  { name: 'Omar Farouk', tagline: 'Venture Capitalist', company: 'Crescent Capital', designation: 'Managing Partner', avatarColor: '#10B981', verified: false, online: true },
  { name: 'Aisha Hussain', tagline: 'Shariah Advisor', company: 'AAOIFI', designation: 'Senior Scholar', avatarColor: '#EC4899', verified: true, online: true },
  { name: 'Yusuf Ibrahim', tagline: 'Tech Entrepreneur', company: 'Halal Startups', designation: 'Founder', avatarColor: '#F59E0B', verified: false, online: false },
  { name: 'Fatima Zahra', tagline: 'ESG Analyst', company: 'MSCI', designation: 'Director', avatarColor: '#8B5CF6', verified: true, online: true },
  { name: 'Khaled Ahmed', tagline: 'Real Estate Developer', company: 'Emirates Properties', designation: 'COO', avatarColor: '#D4A853', verified: false, online: true },
  { name: 'Mariam Ali', tagline: 'Impact Investor', company: 'Islamic Relief', designation: 'Head of Investments', avatarColor: '#EF4444', verified: true, online: false },
];

export const mockRegistrations: Registration[] = [
  {
    id: 'reg1',
    conferenceId: '1',
    conferenceName: 'Global Islamic Finance Summit 2025',
    date: '2025-04-15',
    location: 'Dubai, UAE',
    status: 'upcoming',
    registrationId: 'GIFS2025-380',
    ticketTier: 'VIP',
  },
  {
    id: 'reg2',
    conferenceId: '4',
    conferenceName: 'Education Technology Expo',
    date: '2025-07-08',
    location: 'Toronto, Canada',
    status: 'upcoming',
    registrationId: 'ETE2025-350',
    ticketTier: 'Standard',
  },
  {
    id: 'reg3',
    conferenceId: '2',
    conferenceName: 'TechConnect Innovation Forum',
    date: '2024-12-10',
    location: 'Virtual Event',
    status: 'past',
    registrationId: 'TCIF2024-650',
    ticketTier: 'VIP',
  },
  {
    id: 'reg4',
    conferenceId: '3',
    conferenceName: 'Healthcare Leadership Conference',
    date: '2025-06-20',
    location: 'London, UK',
    status: 'cancelled',
    registrationId: 'HLC2025-180',
    ticketTier: 'Premium',
  },
];
