/**
 * Icon and color mappings for the compact icon sidebar.
 * Kept in sync with Flutter's AppSidebar.
 */

import {
  House, BookOpen, Sparkle, UsersThree, UserPlus, User, ChatCircleDots,
  ChartLineUp, Wallet, CreditCard, Clock, Compass, Calendar, CalendarStar,
  Bell, Info, GearSix, Bank, HandCoins, Briefcase, Lightbulb, Heart,
  HeartStraight, Books, GraduationCap, Star, Storefront, Buildings, FileText,
  IdentificationCard, Microphone, ShieldStar, Heartbeat, Mosque, Lifebuoy,
  Calculator, ChartPieSlice, Flask, WhatsappLogo, TrendUp,
} from '@phosphor-icons/react';
import type { Icon } from '@phosphor-icons/react';

export const ICON_MAP: Record<string, Icon> = {
  Home: House,
  BookOpen,
  Sparkles: Sparkle,
  Sparkle,
  Users: UsersThree,
  UsersRound: UsersThree,
  UserPlus,
  ChatCircleDots,
  User,
  BarChart3: ChartLineUp,
  Calculator,
  Wallet,
  CreditCard,
  Clock,
  Compass,
  Calendar,
  CalendarDays: CalendarStar,
  Bell,
  HelpCircle: Info,
  Settings: GearSix,
  Landmark: Bank,
  HandCoins,
  Briefcase,
  Lightbulb,
  Heart,
  HeartHandshake: HeartStraight,
  Library: Books,
  GraduationCap,
  Star,
  Store: Storefront,
  Building: Buildings,
  FileCheck: FileText,
  IdCard: IdentificationCard,
  Mic: Microphone,
  ShieldCheck: ShieldStar,
  HeartPulse: Heartbeat,
  School: Mosque,
  LifeBuoy: Lifebuoy,
  ChartPie: ChartPieSlice,
  TrendingUp: TrendUp,
  Flask,
  WhatsappLogo,
};

/** Unique color per sidebar icon — matches Flutter Shakir-Theme */
export const ICON_COLOR_MAP: Record<string, string> = {
  home: '#FFFFFF',
  faith: '#E84393',
  quran: '#4A9FD9',
  media: '#4A9FD9',
  ai: '#4FB892',
  'raya-agent': '#25D366',
  screener: '#FFFFFF',
  zakat: '#4FB892',
  wallet: '#4FB892',
  'halal-trading': '#7BB39A',
  'islamic-banking': '#4FB892',
  'barka-labs': '#D4A853',
  prayer: '#7CB3D4',
  qibla: '#4FB892',
  calendar: '#7CB3D4',
  connections: '#22C55E',
  messages: '#D4A853',
  network: '#22C55E',
  matrimony: '#E84393',
  'halal-intimacy': '#E84393',
  events: '#D4A853',
  commerce: '#D4A853',
  souk: '#2A9D6F',
  'real-estate': '#D4A853',
  kyc: '#A855F7',
  'digital-id': '#4FB892',
  voice: '#D4A853',
  admin: '#A855F7',
  tiswa: '#D4A853',
  profile: '#FFFFFF',
  notifications: '#D4A853',
  settings: '#FFFFFF',
  support: '#4FB892',
  help: '#FFFFFF',
  'bait-ul-maal': '#D4A853',
  chamber: '#4FB892',
  'shark-tank': '#D4A853',
  debt: '#4FB892',
  halaqah: '#22C55E',
  'ramadan-kids': '#D4A853',
  education: '#4A9FD9',
};
