/**
 * halaqahShareService — auto-marketing helpers for Halaqah events.
 *
 * Provides:
 *   - Invite URL builder with referral attribution (?ref=<uid>)
 *   - Share-text templates per channel (WhatsApp, SMS, Twitter, generic)
 *   - Lightweight referral log (writes to Firestore so hosts can see attribution)
 *   - Captured-referral helper (call once on app boot to persist any incoming ?ref code)
 */

import { db, auth } from '@/config/firebase.config';
import { addDoc, collection, serverTimestamp } from 'firebase/firestore';

const REFERRAL_KEY = 'zp_halaqah_referrer';

export interface HalaqahShareableEvent {
  id: string;
  name: string;
  date: string;
  startTime: string;
  venue: string;
  hostName: string;
  description?: string;
}

/**
 * Build a shareable invite URL for an event. Adds ?ref=<currentUid> for
 * attribution if the user is signed in. The URL points to the public event
 * page (works without sign-in so non-members can preview before installing
 * the app / signing up).
 */
export function buildInviteUrl(eventId: string, opts?: { baseUrl?: string }): string {
  const base = opts?.baseUrl
    ?? (typeof window !== 'undefined' ? `${window.location.origin}` : 'https://app.zaryahplus.com');
  const me = auth.currentUser?.uid;
  const url = `${base}/halaqah/event/${eventId}`;
  return me ? `${url}?ref=${encodeURIComponent(me)}` : url;
}

/** WhatsApp deep-link helper. Supports mobile WA and Web WhatsApp. */
export function buildWhatsAppLink(text: string): string {
  return `https://wa.me/?text=${encodeURIComponent(text)}`;
}

/** SMS link with prefilled body (works on mobile only). */
export function buildSmsLink(text: string): string {
  return `sms:?&body=${encodeURIComponent(text)}`;
}

/** Twitter compose link. */
export function buildTwitterLink(text: string, url: string): string {
  return `https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}&url=${encodeURIComponent(url)}`;
}

/** Email mailto link. */
export function buildMailtoLink(subject: string, body: string): string {
  return `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
}

/**
 * Default invite copy. Hosts can override before sharing — this is just the
 * starting point. Includes a tasteful Islamic greeting.
 */
export function buildShareText(event: HalaqahShareableEvent, url: string): string {
  return [
    `Assalamu Alaikum 🌙`,
    ``,
    `You're invited to "${event.name}" hosted by ${event.hostName}.`,
    ``,
    `📅 ${event.date} at ${event.startTime}`,
    `📍 ${event.venue}`,
    ``,
    `RSVP & details: ${url}`,
  ].join('\n');
}

/** Short variant for SMS / Twitter where space is tight. */
export function buildShortShareText(event: HalaqahShareableEvent, url: string): string {
  return `Halaqah: ${event.name} — ${event.date} ${event.startTime} at ${event.venue}. ${url}`;
}

/** Capture an incoming ?ref=<uid> from the URL and persist it. Call on app boot. */
export function captureIncomingReferral(): void {
  if (typeof window === 'undefined') return;
  try {
    const params = new URLSearchParams(window.location.search);
    const ref = params.get('ref');
    if (ref && /^[A-Za-z0-9_-]{8,128}$/.test(ref)) {
      // Don't overwrite an existing referrer — first one wins.
      if (!localStorage.getItem(REFERRAL_KEY)) {
        localStorage.setItem(REFERRAL_KEY, ref);
        localStorage.setItem(REFERRAL_KEY + '_at', String(Date.now()));
      }
    }
  } catch { /* ignore */ }
}

export function getCapturedReferrer(): string | null {
  try { return localStorage.getItem(REFERRAL_KEY); } catch { return null; }
}

/**
 * Log a share event so hosts can see attribution analytics. Best-effort,
 * non-blocking. Writes to halaqah_share_events/{auto-id}.
 */
export async function logShareEvent(eventId: string, channel: 'whatsapp' | 'sms' | 'twitter' | 'email' | 'native' | 'copy' | 'qr'): Promise<void> {
  const me = auth.currentUser?.uid;
  if (!me) return;
  try {
    await addDoc(collection(db, 'halaqah_share_events'), {
      eventId,
      sharedBy: me,
      channel,
      createdAt: serverTimestamp(),
    });
  } catch (err) {
    console.warn('[halaqah] share log failed:', err);
  }
}

/**
 * Log when a user lands on a public event page from a referral link. The host
 * can later see "X clicks generated by Y referrer".
 */
export async function logEventLanding(eventId: string, referrer: string | null): Promise<void> {
  try {
    await addDoc(collection(db, 'halaqah_landing_events'), {
      eventId,
      referrer: referrer || null,
      visitorUid: auth.currentUser?.uid || null,
      createdAt: serverTimestamp(),
    });
  } catch { /* ignore */ }
}
