/**
 * Mock data for the Halaqah Admin page.
 *
 * Phase 5 split — extracted from HalaqahAdminPage.tsx. Pure data; no
 * behaviour change.
 */

import type { Activity, ApprovedEvent, Host, PendingEvent } from './_types';

export const MOCK_PENDING_EVENTS: PendingEvent[] = [
  {
    id: 'pe1',
    name: 'Tafsir Al-Baqarah Study Circle',
    category: 'Quran Study',
    date: '2026-02-20',
    hostName: 'Sheikh Ahmad Hassan',
    hostEmail: 'ahmad.hassan@example.com',
    capacity: 50,
    venue: 'Green Valley Masjid',
    description: 'Deep dive into Surah Al-Baqarah verses 1-50 with classical commentaries',
    agenda: ['Recitation and Translation', 'Tafsir Discussion', 'Q&A Session', 'Closing Dua'],
    submittedAt: '2026-02-10T14:30:00',
  },
  {
    id: 'pe2',
    name: 'Youth Leadership Workshop',
    category: 'Youth Program',
    date: '2026-02-22',
    hostName: 'Fatima Al-Noor',
    hostEmail: 'fatima.noor@example.com',
    capacity: 35,
    venue: 'Community Center Hall B',
    description: 'Empowering young Muslims to become community leaders',
    agenda: ['Leadership in Islam', 'Interactive Activities', 'Group Projects', 'Certificates'],
    submittedAt: '2026-02-11T09:15:00',
  },
  {
    id: 'pe3',
    name: 'Hadith Authentication Methods',
    category: 'Hadith Discussion',
    date: '2026-02-25',
    hostName: 'Dr. Ibrahim Khalil',
    hostEmail: 'ibrahim.khalil@example.com',
    capacity: 40,
    venue: 'Islamic Institute Lecture Hall',
    description: 'Learn the science of Hadith authentication from classical scholars',
    agenda: ['Introduction to Ilm al-Hadith', 'Chain of Narration', 'Practical Examples', 'Discussion'],
    submittedAt: '2026-02-11T16:45:00',
  },
  {
    id: 'pe4',
    name: 'Family Fun Day',
    category: 'Family Event',
    date: '2026-02-28',
    hostName: 'Aisha Rahman',
    hostEmail: 'aisha.rahman@example.com',
    capacity: 100,
    venue: 'Central Park Pavilion',
    description: 'Family-friendly activities, food, and entertainment for all ages',
    agenda: ['Opening Prayer', 'Kids Activities', 'Lunch', 'Sports & Games', 'Closing'],
    submittedAt: '2026-02-12T08:00:00',
  },
  {
    id: 'pe5',
    name: 'Charity Fundraiser Dinner',
    category: 'Charity',
    date: '2026-03-05',
    hostName: 'Yusuf Mohammed',
    hostEmail: 'yusuf.mohammed@example.com',
    capacity: 150,
    venue: 'Grand Ballroom Hotel',
    description: 'Annual charity dinner to support orphans in Palestine',
    agenda: ['Welcome Reception', 'Dinner', 'Keynote Speech', 'Fundraising Auction', 'Closing Remarks'],
    submittedAt: '2026-02-12T10:30:00',
  },
  {
    id: 'pe6',
    name: 'Dawah Training Workshop',
    category: 'Dawah',
    date: '2026-03-08',
    hostName: 'Bilal Ahmed',
    hostEmail: 'bilal.ahmed@example.com',
    capacity: 30,
    venue: 'Downtown Masjid Conference Room',
    description: 'Learn effective dawah techniques with wisdom and compassion',
    agenda: ['Islamic Dawah Principles', 'Communication Skills', 'Role Play', 'Resource Materials'],
    submittedAt: '2026-02-12T11:00:00',
  },
];

export const MOCK_APPROVED_EVENTS: ApprovedEvent[] = [
  {
    id: 'ae1',
    name: 'Friday Quran Recitation',
    category: 'Quran Study',
    date: '2026-02-14',
    attendees: 42,
    capacity: 50,
    location: 'Main Masjid',
    description: 'Weekly Quran recitation with Tajweed corrections',
    hostName: 'Sheikh Abdullah',
    approvedAt: '2026-02-05T10:00:00',
    attendeesList: [
      { name: 'Ali Hassan', email: 'ali@example.com', registeredAt: '2026-02-06T14:20:00' },
      { name: 'Sara Ahmed', email: 'sara@example.com', registeredAt: '2026-02-06T15:10:00' },
      { name: 'Omar Farooq', email: 'omar@example.com', registeredAt: '2026-02-07T09:30:00' },
    ],
  },
  {
    id: 'ae2',
    name: 'Islamic Finance Seminar',
    category: 'Education',
    date: '2026-02-16',
    attendees: 65,
    capacity: 80,
    location: 'University Auditorium',
    description: 'Understanding halal investment and Islamic banking principles',
    hostName: 'Dr. Zaynab Ibrahim',
    approvedAt: '2026-02-03T14:30:00',
    attendeesList: [
      { name: 'Hassan Ali', email: 'hassan@example.com', registeredAt: '2026-02-04T10:00:00' },
      { name: 'Maryam Yusuf', email: 'maryam@example.com', registeredAt: '2026-02-04T11:30:00' },
    ],
  },
  {
    id: 'ae3',
    name: 'Community Iftar Planning',
    category: 'Community Gathering',
    date: '2026-02-18',
    attendees: 28,
    capacity: 40,
    location: 'Community Center',
    description: 'Planning session for upcoming Ramadan community iftars',
    hostName: 'Khadija Hassan',
    approvedAt: '2026-02-01T09:00:00',
    attendeesList: [
      { name: 'Fatima Noor', email: 'fatima@example.com', registeredAt: '2026-02-02T16:00:00' },
    ],
  },
  {
    id: 'ae4',
    name: 'Prophetic Medicine Workshop',
    category: 'Islamic Lecture',
    date: '2026-02-21',
    attendees: 55,
    capacity: 60,
    location: 'Medical Institute Hall',
    description: 'Exploring traditional Islamic healing methods and modern medicine',
    hostName: 'Dr. Umar Malik',
    approvedAt: '2026-02-08T13:00:00',
    attendeesList: [
      { name: 'Aisha Rahman', email: 'aisha.r@example.com', registeredAt: '2026-02-09T08:00:00' },
      { name: 'Ibrahim Syed', email: 'ibrahim@example.com', registeredAt: '2026-02-09T12:00:00' },
    ],
  },
  {
    id: 'ae5',
    name: 'Sisters Circle - Spiritual Growth',
    category: 'Community Gathering',
    date: '2026-02-23',
    attendees: 32,
    capacity: 35,
    location: 'Sisters Prayer Hall',
    description: 'Monthly gathering for spiritual discussions and sisterhood',
    hostName: 'Sumayyah Ali',
    approvedAt: '2026-02-07T15:00:00',
    attendeesList: [
      { name: 'Hafsa Ahmed', email: 'hafsa@example.com', registeredAt: '2026-02-08T10:00:00' },
    ],
  },
  {
    id: 'ae6',
    name: 'Youth Sports Tournament',
    category: 'Youth Program',
    date: '2026-02-26',
    attendees: 78,
    capacity: 100,
    location: 'Sports Complex',
    description: 'Basketball and soccer tournament for Muslim youth',
    hostName: 'Coach Tariq Hassan',
    approvedAt: '2026-02-04T11:00:00',
    attendeesList: [
      { name: 'Zayd Omar', email: 'zayd@example.com', registeredAt: '2026-02-05T14:00:00' },
      { name: 'Hamza Malik', email: 'hamza@example.com', registeredAt: '2026-02-05T15:30:00' },
    ],
  },
  {
    id: 'ae7',
    name: 'Marriage Preparation Course',
    category: 'Family Event',
    date: '2026-03-01',
    attendees: 24,
    capacity: 30,
    location: 'Counseling Center',
    description: 'Islamic guidance for couples preparing for marriage',
    hostName: 'Sheikh Yasir & Sister Amina',
    approvedAt: '2026-02-09T10:00:00',
    attendeesList: [
      { name: 'Ahmed & Layla', email: 'ahmed@example.com', registeredAt: '2026-02-10T09:00:00' },
    ],
  },
  {
    id: 'ae8',
    name: 'Ramadan Preparation Lecture',
    category: 'Islamic Lecture',
    date: '2026-03-03',
    attendees: 89,
    capacity: 100,
    location: 'Grand Masjid',
    description: 'Preparing spiritually and practically for the blessed month',
    hostName: 'Imam Khalid Rahman',
    approvedAt: '2026-02-06T16:00:00',
    attendeesList: [
      { name: 'Bilal Hassan', email: 'bilal@example.com', registeredAt: '2026-02-07T10:00:00' },
      { name: 'Noor Ahmed', email: 'noor@example.com', registeredAt: '2026-02-07T11:00:00' },
    ],
  },
];

export const MOCK_HOSTS: Host[] = [
  {
    id: 'h1',
    name: 'Sheikh Ahmad Hassan',
    email: 'ahmad.hassan@example.com',
    verified: true,
    eventsHosted: 12,
    rating: 4.8,
    joinedDate: '2025-06-15',
    phone: '+1-555-0101',
    bio: 'Islamic scholar with 15 years of teaching experience',
  },
  {
    id: 'h2',
    name: 'Dr. Zaynab Ibrahim',
    email: 'zaynab.ibrahim@example.com',
    verified: true,
    eventsHosted: 8,
    rating: 4.9,
    joinedDate: '2025-07-20',
    phone: '+1-555-0102',
    bio: 'PhD in Islamic Finance, university professor',
  },
  {
    id: 'h3',
    name: 'Fatima Al-Noor',
    email: 'fatima.noor@example.com',
    verified: false,
    eventsHosted: 3,
    rating: 4.5,
    joinedDate: '2025-11-10',
    phone: '+1-555-0103',
    bio: 'Youth coordinator and community organizer',
  },
  {
    id: 'h4',
    name: 'Imam Khalid Rahman',
    email: 'khalid.rahman@example.com',
    verified: true,
    eventsHosted: 15,
    rating: 5.0,
    joinedDate: '2025-05-01',
    phone: '+1-555-0104',
    bio: 'Community Imam and spiritual advisor',
  },
  {
    id: 'h5',
    name: 'Dr. Umar Malik',
    email: 'umar.malik@example.com',
    verified: true,
    eventsHosted: 6,
    rating: 4.7,
    joinedDate: '2025-08-15',
    phone: '+1-555-0105',
    bio: 'Medical doctor specializing in Islamic medicine',
  },
  {
    id: 'h6',
    name: 'Aisha Rahman',
    email: 'aisha.rahman@example.com',
    verified: false,
    eventsHosted: 2,
    rating: 4.3,
    joinedDate: '2025-12-01',
    phone: '+1-555-0106',
    bio: 'Event planner and family program coordinator',
  },
  {
    id: 'h7',
    name: 'Yusuf Mohammed',
    email: 'yusuf.mohammed@example.com',
    verified: true,
    eventsHosted: 10,
    rating: 4.6,
    joinedDate: '2025-06-30',
    phone: '+1-555-0107',
    bio: 'Charity director and fundraising specialist',
  },
  {
    id: 'h8',
    name: 'Bilal Ahmed',
    email: 'bilal.ahmed@example.com',
    verified: false,
    eventsHosted: 4,
    rating: 4.4,
    joinedDate: '2025-10-15',
    phone: '+1-555-0108',
    bio: 'Dawah coordinator and public speaker',
  },
];

export const MOCK_ACTIVITIES: Activity[] = [
  {
    id: 'act1',
    action: 'Approved',
    eventName: 'Friday Quran Recitation',
    timestamp: '2026-02-05T10:00:00',
    type: 'approved',
  },
  {
    id: 'act2',
    action: 'Rejected',
    eventName: 'Unauthorized Gathering',
    timestamp: '2026-02-06T14:30:00',
    type: 'rejected',
  },
  {
    id: 'act3',
    action: 'Approved',
    eventName: 'Islamic Finance Seminar',
    timestamp: '2026-02-03T14:30:00',
    type: 'approved',
  },
  {
    id: 'act4',
    action: 'Verified Host',
    eventName: 'Dr. Zaynab Ibrahim',
    timestamp: '2026-02-07T09:00:00',
    type: 'verified',
  },
  {
    id: 'act5',
    action: 'Approved',
    eventName: 'Ramadan Preparation Lecture',
    timestamp: '2026-02-06T16:00:00',
    type: 'approved',
  },
];
