/**
 * Mock data for the TISWA page. Phase 5 split.
 */

// Mock Data
export const NETWORK_SCHOOLS = [
  {
    id: '1',
    name: 'Al-Huda Islamic School',
    address: 'Chennai, Tamil Nadu',
    teachers: 24,
    students: 380,
    resources: 45,
    followers: 156,
    membership: 'PREMIUM',
    connected: true,
  },
  {
    id: '2',
    name: 'Noor Academy',
    address: 'Madurai, Tamil Nadu',
    teachers: 18,
    students: 250,
    resources: 32,
    followers: 89,
    membership: 'BASIC',
    connected: false,
  },
  {
    id: '3',
    name: 'Crescent Public School',
    address: 'Coimbatore, Tamil Nadu',
    teachers: 30,
    students: 520,
    resources: 67,
    followers: 203,
    membership: 'PREMIUM',
    connected: true,
  },
  {
    id: '4',
    name: 'Islamic Foundation School',
    address: 'Trichy, Tamil Nadu',
    teachers: 15,
    students: 180,
    resources: 23,
    followers: 67,
    membership: 'BASIC',
    connected: false,
  },
];

export const SHARED_RESOURCES = [
  {
    id: '1',
    title: 'Advanced Mathematics Workbook',
    school: 'Al-Huda Islamic School',
    type: 'PDF',
    subject: 'Mathematics',
    grade: 'Grade 10',
    description: 'Comprehensive workbook covering algebra, geometry, and trigonometry with practice problems and solutions.',
    downloads: 145,
    uploader: 'Dr. Ahmed Khan',
    date: '2025-01-10',
    icon: 'document',
  },
  {
    id: '2',
    title: 'Science Lab Manual 2025',
    school: 'Noor Academy',
    type: 'PDF',
    subject: 'Science',
    grade: 'Grade 11',
    description: 'Complete laboratory manual with experiments, safety guidelines, and observation templates for physics, chemistry, and biology.',
    downloads: 89,
    uploader: 'Prof. Fatima Rahman',
    date: '2025-01-08',
    icon: 'document',
  },
  {
    id: '3',
    title: 'English Literature Guide',
    school: 'Crescent Public School',
    type: 'Document',
    subject: 'English',
    grade: 'Grade 9',
    description: 'Study guide for classic English literature with chapter summaries, character analysis, and essay writing tips.',
    downloads: 67,
    uploader: 'Ms. Zainab Ali',
    date: '2025-01-05',
    icon: 'document',
  },
];

export const ASSIGNMENTS_DATA = [
  {
    id: '1',
    title: 'Algebra Problem Set',
    subject: 'Mathematics',
    dueDate: '2025-01-20',
    status: 'pending',
    priority: 'high',
    description: 'Complete problems 1-25 from Chapter 5. Show all work and write final answers clearly.',
    instructions: 'Solve all algebraic equations and inequalities. Use the quadratic formula where necessary. Submit handwritten or typed solutions.',
    grade: null,
    feedback: null,
  },
  {
    id: '2',
    title: 'Physics Lab Report',
    subject: 'Science',
    dueDate: '2025-01-22',
    status: 'pending',
    priority: 'normal',
    description: 'Write a detailed lab report on the pendulum experiment conducted last week.',
    instructions: 'Include hypothesis, methodology, observations, calculations, results, and conclusion. Follow the lab report template provided.',
    grade: null,
    feedback: null,
  },
  {
    id: '3',
    title: 'Essay on Islamic History',
    subject: 'History',
    dueDate: '2025-01-18',
    status: 'pending',
    priority: 'high',
    description: 'Write a 1000-word essay on the Golden Age of Islam and its contributions to science.',
    instructions: 'Cover at least three major scientific achievements. Use proper citations and include a bibliography.',
    grade: null,
    feedback: null,
    overdue: true,
  },
  {
    id: '4',
    title: 'English Grammar Worksheet',
    subject: 'English',
    dueDate: '2025-01-15',
    status: 'submitted',
    priority: 'normal',
    description: 'Complete the grammar worksheet on active and passive voice.',
    instructions: 'Convert 20 sentences from active to passive voice and vice versa.',
    grade: null,
    feedback: null,
  },
  {
    id: '5',
    title: 'Geography Map Activity',
    subject: 'Geography',
    dueDate: '2025-01-12',
    status: 'graded',
    priority: 'normal',
    description: 'Label the major rivers, mountains, and cities of Tamil Nadu on the provided map.',
    instructions: 'Use the atlas for reference. Write labels clearly and ensure accuracy.',
    grade: 85,
    feedback: 'Good work! Minor errors in river names. Study the map more carefully.',
  },
  {
    id: '6',
    title: 'Computer Science Project',
    subject: 'Computer Science',
    dueDate: '2025-01-10',
    status: 'graded',
    priority: 'normal',
    description: 'Create a simple calculator program using Python.',
    instructions: 'Implement addition, subtraction, multiplication, and division. Include error handling for division by zero.',
    grade: 92,
    feedback: 'Excellent! Clean code with proper error handling. Great job!',
  },
];

export const TODAYS_CLASSES = [
  {
    id: '1',
    time: '8:00-8:45',
    subject: 'Mathematics',
    class: '10-A',
    room: 'Room 101',
    students: 30,
    status: 'completed',
    topic: 'Quadratic Equations',
  },
  {
    id: '2',
    time: '9:00-9:45',
    subject: 'Mathematics',
    class: '10-B',
    room: 'Room 102',
    students: 28,
    status: 'completed',
    topic: 'Quadratic Equations',
  },
  {
    id: '3',
    time: '10:00-10:45',
    subject: 'Physics',
    class: '11-A',
    room: 'Lab 1',
    students: 25,
    status: 'ongoing',
    topic: 'Simple Harmonic Motion',
  },
  {
    id: '4',
    time: '11:00-11:45',
    subject: 'Physics',
    class: '11-B',
    room: 'Lab 2',
    students: 27,
    status: 'upcoming',
    topic: 'Simple Harmonic Motion',
  },
  {
    id: '5',
    time: '1:00-1:45',
    subject: 'Mathematics',
    class: '9-A',
    room: 'Room 103',
    students: 32,
    status: 'upcoming',
    topic: 'Linear Equations',
  },
  {
    id: '6',
    time: '2:00-2:45',
    subject: 'Physics',
    class: '9-B',
    room: 'Lab 1',
    students: 30,
    status: 'upcoming',
    topic: 'Force and Motion',
  },
];

export const NETWORK_FEED = [
  {
    id: '1',
    school: 'Al-Huda Islamic School',
    type: 'resource',
    title: 'New Chemistry Lab Equipment Available',
    content: 'Our school has acquired new chemistry lab equipment. Available for use by network schools.',
    timestamp: '2 hours ago',
  },
  {
    id: '2',
    school: 'Crescent Public School',
    type: 'news',
    title: 'Inter-School Science Competition Announced',
    content: 'Registration open for the annual TISWA Science Fair. Deadline: January 25, 2025.',
    timestamp: '5 hours ago',
  },
  {
    id: '3',
    school: 'Noor Academy',
    type: 'resource',
    title: 'Online Mathematics Tutorial Series',
    content: 'Free tutorial videos for Grade 10 Mathematics now available on our platform.',
    timestamp: '1 day ago',
  },
];

export const TEACHER_RECENT_ACTIVITY = [
  {
    id: '1',
    type: 'submission',
    student: 'Ahmad Ibrahim',
    action: 'submitted',
    item: 'Physics Lab Report',
    time: '10 minutes ago',
  },
  {
    id: '2',
    type: 'request',
    student: 'Zainab Hassan',
    action: 'requested to join',
    item: 'Class 10-A',
    time: '1 hour ago',
  },
  {
    id: '3',
    type: 'message',
    student: 'Ibrahim Ali',
    action: 'sent a message about',
    item: 'Assignment clarification',
    time: '2 hours ago',
  },
  {
    id: '4',
    type: 'submission',
    student: 'Fatima Begum',
    action: 'submitted',
    item: 'Mathematics Problem Set',
    time: '3 hours ago',
  },
  {
    id: '5',
    type: 'request',
    student: 'Ali Rahman',
    action: 'requested access to',
    item: 'Study Materials',
    time: '5 hours ago',
  },
];

export const ADMIN_RECENT_ACTIVITY = [
  {
    id: '1',
    type: 'approval',
    user: 'Ms. Sarah Khan',
    action: 'approved as teacher',
    item: 'Al-Huda Islamic School',
    time: '30 minutes ago',
    color: '#10B981',
  },
  {
    id: '2',
    type: 'content',
    user: 'System',
    action: 'uploaded',
    item: 'Mathematics Workbook',
    time: '2 hours ago',
    color: '#D4A853',
  },
  {
    id: '3',
    type: 'event',
    user: 'Crescent Public School',
    action: 'created event',
    item: 'Science Fair 2025',
    time: '4 hours ago',
    color: '#8B5CF6',
  },
  {
    id: '4',
    type: 'request',
    user: 'Mr. Ahmed Malik',
    action: 'requested teacher access',
    item: 'Noor Academy',
    time: '6 hours ago',
    color: '#F59E0B',
  },
  {
    id: '5',
    type: 'content',
    user: 'System',
    action: 'reviewed and approved',
    item: 'Science Lab Manual',
    time: '1 day ago',
    color: '#10B981',
  },
];

export const TISWA_ADMIN_ACTIVITY = [
  {
    id: '1',
    type: 'system',
    action: 'School approval request',
    item: 'Madina Islamic School - Requires verification',
    time: '15 minutes ago',
    color: '#EF4444',
  },
  {
    id: '2',
    type: 'moderation',
    action: 'Content flagged',
    item: 'User-uploaded resource requires review',
    time: '1 hour ago',
    color: '#F59E0B',
  },
  {
    id: '3',
    type: 'support',
    action: 'Support ticket',
    item: 'Teacher unable to access content library',
    time: '2 hours ago',
    color: '#D4A853',
  },
  {
    id: '4',
    type: 'system',
    action: 'System update',
    item: 'Database backup completed successfully',
    time: '4 hours ago',
    color: '#10B981',
  },
  {
    id: '5',
    type: 'approval',
    action: 'School approved',
    item: 'Islamic Foundation School - Premium tier',
    time: '6 hours ago',
    color: '#10B981',
  },
];

export const URGENT_ITEMS = [
  {
    id: '1',
    title: 'School Verification Pending',
    description: 'Madina Islamic School awaiting document verification - 3 days overdue',
    priority: 'critical',
  },
  {
    id: '2',
    title: 'Flagged Content Review',
    description: '5 uploaded resources flagged by automated system - require manual review',
    priority: 'high',
  },
];
