/**
 * Mock data for ChamberV2. Phase 5 split.
 */

import type { Member, NetworkingSession, Presentation, Referral } from './_types';

export const mockMembers: Member[] = [
  {
    id: '1',
    name: 'Ahmed Al-Rashid',
    role: 'Chief Technology Officer',
    company: 'TechVentures MENA',
    verified: true,
    premium: true,
    bio: 'Leading digital transformation in Islamic fintech. Passionate about building ethical tech solutions.',
    location: 'Dubai, UAE',
    connections: 342,
    category: 'Technology',
    avatar: 'AR',
    skills: ['Fintech', 'Blockchain', 'AI/ML', 'Product Strategy'],
    experience: [
      { title: 'CTO', company: 'TechVentures MENA', period: '2022 - Present' },
      { title: 'VP Engineering', company: 'Digital Horizons', period: '2019 - 2022' },
    ],
    activityCount: 28,
  },
  {
    id: '2',
    name: 'Fatima Hassan',
    role: 'Investment Director',
    company: 'Crescent Capital',
    verified: true,
    premium: true,
    bio: 'Sharia-compliant investment specialist with 15+ years experience in Islamic finance and venture capital.',
    location: 'Riyadh, Saudi Arabia',
    connections: 567,
    category: 'Finance',
    avatar: 'FH',
    skills: ['Islamic Finance', 'VC', 'Due Diligence', 'Portfolio Management'],
    experience: [
      { title: 'Investment Director', company: 'Crescent Capital', period: '2020 - Present' },
      { title: 'Senior Analyst', company: 'Gulf Investments', period: '2015 - 2020' },
    ],
    activityCount: 45,
  },
  {
    id: '3',
    name: 'Omar Suleiman',
    role: 'Healthcare Entrepreneur',
    company: 'MedWell Clinics',
    verified: true,
    premium: false,
    bio: 'Building accessible healthcare solutions across the MENA region. Focus on telemedicine and community health.',
    location: 'Cairo, Egypt',
    connections: 234,
    category: 'Healthcare',
    avatar: 'OS',
    skills: ['Healthcare Operations', 'Telemedicine', 'Business Development'],
    experience: [
      { title: 'Founder & CEO', company: 'MedWell Clinics', period: '2021 - Present' },
    ],
    activityCount: 19,
  },
  {
    id: '4',
    name: 'Aisha Malik',
    role: 'Real Estate Developer',
    company: 'Urban Living Co.',
    verified: true,
    premium: true,
    bio: 'Specializing in sustainable urban development and smart city projects with Islamic investment structures.',
    location: 'Doha, Qatar',
    connections: 456,
    category: 'Real Estate',
    avatar: 'AM',
    skills: ['Property Development', 'Urban Planning', 'Islamic REITs'],
    experience: [
      { title: 'Development Director', company: 'Urban Living Co.', period: '2019 - Present' },
    ],
    activityCount: 33,
  },
  {
    id: '5',
    name: 'Yusuf Ibrahim',
    role: 'Education Innovator',
    company: 'LearnHub Academy',
    verified: false,
    premium: false,
    bio: 'Transforming education through technology. Creating accessible learning platforms for Muslim communities.',
    location: 'Kuala Lumpur, Malaysia',
    connections: 189,
    category: 'Education',
    avatar: 'YI',
    skills: ['EdTech', 'Curriculum Design', 'Online Learning'],
    experience: [
      { title: 'Founder', company: 'LearnHub Academy', period: '2022 - Present' },
    ],
    activityCount: 15,
  },
  {
    id: '6',
    name: 'Zainab Ali',
    role: 'Marketing Strategist',
    company: 'Brand Builders',
    verified: true,
    premium: false,
    bio: 'Helping halal businesses reach global markets. Expert in digital marketing and brand positioning.',
    location: 'Istanbul, Turkey',
    connections: 298,
    category: 'Marketing',
    avatar: 'ZA',
    skills: ['Digital Marketing', 'Brand Strategy', 'Social Media', 'Content'],
    experience: [
      { title: 'Strategy Director', company: 'Brand Builders', period: '2020 - Present' },
    ],
    activityCount: 22,
  },
];

export const mockReferrals: Referral[] = [
  {
    id: 'r1',
    fromMember: 'You',
    toMember: 'Ahmed Al-Rashid',
    type: 'Business Opportunity',
    status: 'completed',
    details: 'Fintech partnership opportunity for Islamic banking app integration',
    value: '$250K',
    date: '2024-01-15',
  },
  {
    id: 'r2',
    fromMember: 'You',
    toMember: 'Fatima Hassan',
    type: 'Investment',
    status: 'accepted',
    details: 'Series A funding round for halal food delivery startup',
    value: '$2M',
    date: '2024-01-20',
  },
  {
    id: 'r3',
    fromMember: 'You',
    toMember: 'Omar Suleiman',
    type: 'Partnership',
    status: 'pending',
    details: 'Strategic partnership for telemedicine platform expansion',
    value: '$500K',
    date: '2024-01-25',
  },
  {
    id: 'r4',
    fromMember: 'Ahmed Al-Rashid',
    toMember: 'You',
    type: 'Client Introduction',
    status: 'pending',
    details: 'Introduction to major Islamic bank for technology consulting services',
    value: '$150K',
    date: '2024-01-22',
  },
  {
    id: 'r5',
    fromMember: 'Fatima Hassan',
    toMember: 'You',
    type: 'Mentorship',
    status: 'accepted',
    details: 'Mentorship opportunity for Islamic finance certification program',
    value: 'N/A',
    date: '2024-01-18',
  },
];

export const mockSessions: NetworkingSession[] = [
  {
    id: 's1',
    title: 'Islamic Fintech Innovation Summit',
    description: 'Exploring the future of Sharia-compliant digital banking and investment platforms',
    time: 'Today, 3:00 PM',
    duration: '90 min',
    host: 'Ahmed Al-Rashid',
    hostRole: 'CTO, TechVentures MENA',
    attendees: 42,
    capacity: 50,
    category: 'Technology',
  },
  {
    id: 's2',
    title: 'Investment Opportunities in Gulf Markets',
    description: 'Deep dive into Sharia-compliant investment strategies for 2024',
    time: 'Tomorrow, 10:00 AM',
    duration: '60 min',
    host: 'Fatima Hassan',
    hostRole: 'Investment Director, Crescent Capital',
    attendees: 38,
    capacity: 40,
    category: 'Investment',
  },
  {
    id: 's3',
    title: 'Real Estate Sukuk Masterclass',
    description: 'Understanding Islamic REITs and property-backed securities',
    time: 'Jan 30, 2:00 PM',
    duration: '120 min',
    host: 'Aisha Malik',
    hostRole: 'Real Estate Developer',
    attendees: 28,
    capacity: 35,
    category: 'Real Estate',
  },
  {
    id: 's4',
    title: 'Healthcare Innovation Forum',
    description: 'Discussing technology solutions for accessible Muslim healthcare',
    time: 'Feb 1, 4:00 PM',
    duration: '75 min',
    host: 'Omar Suleiman',
    hostRole: 'Healthcare Entrepreneur',
    attendees: 19,
    capacity: 30,
    category: 'Healthcare',
  },
  {
    id: 's5',
    title: 'Startup Pitch Night',
    description: 'Early-stage halal startups presenting to angel investors',
    time: 'Feb 5, 6:00 PM',
    duration: '120 min',
    host: 'Yusuf Ibrahim',
    hostRole: 'Education Innovator',
    attendees: 55,
    capacity: 60,
    category: 'Startups',
  },
  {
    id: 's6',
    title: 'Islamic Finance Fundamentals',
    description: 'Introduction to Sharia-compliant business structures and contracts',
    time: 'Feb 8, 11:00 AM',
    duration: '90 min',
    host: 'Fatima Hassan',
    hostRole: 'Investment Director',
    attendees: 31,
    capacity: 45,
    category: 'Islamic Finance',
  },
];

export const mockPresentations: Presentation[] = [
  {
    id: 'p1',
    title: 'Islamic Fintech Trends 2024',
    owner: 'Ahmed Al-Rashid',
    verified: true,
    slides: 42,
    views: 3240,
    likes: 287,
    featured: true,
    category: 'Technology',
    thumbnail: 'tech',
    description: 'Comprehensive analysis of emerging trends in Islamic fintech including blockchain, digital banking, and DeFi alternatives.',
  },
  {
    id: 'p2',
    title: 'Sharia-Compliant Investment Strategy',
    owner: 'Fatima Hassan',
    verified: true,
    slides: 38,
    views: 2890,
    likes: 312,
    featured: true,
    category: 'Investment',
    thumbnail: 'invest',
    description: 'Complete guide to building diversified portfolios using Islamic financial instruments.',
  },
  {
    id: 'p3',
    title: 'Startup Funding Roadmap',
    owner: 'Yusuf Ibrahim',
    verified: false,
    slides: 28,
    views: 1567,
    likes: 143,
    featured: false,
    category: 'Startup',
    thumbnail: 'startup',
    description: 'Step-by-step guide for early-stage entrepreneurs seeking halal funding.',
  },
  {
    id: 'p4',
    title: 'Real Estate Sukuk Overview',
    owner: 'Aisha Malik',
    verified: true,
    slides: 35,
    views: 2134,
    likes: 198,
    featured: true,
    category: 'Islamic Finance',
    thumbnail: 'finance',
    description: 'Understanding property-backed Islamic securities and investment opportunities.',
  },
  {
    id: 'p5',
    title: 'Digital Marketing for Halal Brands',
    owner: 'Zainab Ali',
    verified: true,
    slides: 31,
    views: 1876,
    likes: 167,
    featured: false,
    category: 'Marketing',
    thumbnail: 'marketing',
    description: 'Effective strategies for promoting halal businesses in the digital age.',
  },
  {
    id: 'p6',
    title: 'Healthcare Tech Business Plan',
    owner: 'Omar Suleiman',
    verified: true,
    slides: 45,
    views: 1234,
    likes: 109,
    featured: false,
    category: 'Business Plan',
    thumbnail: 'health',
    description: 'Complete business plan template for healthcare technology startups.',
  },
  {
    id: 'p7',
    title: 'Blockchain in Islamic Finance',
    owner: 'Ahmed Al-Rashid',
    verified: true,
    slides: 52,
    views: 2987,
    likes: 341,
    featured: true,
    category: 'Technology',
    thumbnail: 'blockchain',
    description: 'How distributed ledger technology is transforming Islamic banking.',
  },
  {
    id: 'p8',
    title: 'Gulf Market Entry Strategy',
    owner: 'Fatima Hassan',
    verified: true,
    slides: 29,
    views: 1654,
    likes: 156,
    featured: false,
    category: 'Business Plan',
    thumbnail: 'market',
    description: 'Strategic framework for entering GCC markets with halal products.',
  },
];

export const myDecks: Presentation[] = [
  {
    id: 'md1',
    title: 'Q1 Chamber Growth Strategy',
    owner: 'You',
    verified: false,
    slides: 24,
    views: 0,
    likes: 0,
    featured: false,
    category: 'Business Plan',
    thumbnail: 'strategy',
    status: 'draft',
  },
  {
    id: 'md2',
    title: 'Member Success Stories 2023',
    owner: 'You',
    verified: false,
    slides: 18,
    views: 456,
    likes: 42,
    featured: false,
    category: 'Marketing',
    thumbnail: 'stories',
    status: 'published',
  },
  {
    id: 'md3',
    title: 'Chamber Analytics Overview',
    owner: 'You',
    verified: false,
    slides: 15,
    views: 234,
    likes: 28,
    featured: false,
    category: 'Other',
    thumbnail: 'analytics',
    status: 'published',
  },
];

