/**
 * Mock Halaqah events used for demos and tests.
 */

import type { HalaqahEvent } from './_types';

export const mockEvents: HalaqahEvent[] = [
  {
    id: '1',
    name: 'Weekly Quran Study Circle',
    category: 'quran',
    date: '2025-01-15',
    startTime: '2:00 PM',
    endTime: '4:00 PM',
    venue: 'Masjid Al-Noor',
    venueAddress: '123 Main Street, Downtown, City 12345',
    capacity: 30,
    attendeeCount: 22,
    status: 'approved',
    description: 'Join us for an in-depth study of Surah Al-Kahf with Tafsir insights and reflection on its timeless wisdom.',
    hostName: 'Sheikh Ahmad Abdullah',
    hostId: 'host1',
    hostRating: 4.9,
    hostVerified: true,
    agenda: [
      { title: 'Quran Recitation', arabicTitle: 'تلاوة القرآن', duration: 30 },
      { title: 'Tafsir Discussion', arabicTitle: 'مناقشة التفسير', duration: 60 },
      { title: 'Q&A Session', arabicTitle: 'جلسة أسئلة وأجوبة', duration: 30 },
    ],
    venueFeatures: {
      qiblaDirection: true,
      prayerSpace: true,
      wuduFacilities: true,
      parking: true,
      wheelchairAccessible: true,
    },
    registeredCount: 22,
    checkedInCount: 18,
  },
  {
    id: '2',
    name: 'Hadith Sciences Workshop',
    category: 'hadith',
    date: '2025-01-18',
    startTime: '10:00 AM',
    endTime: '1:00 PM',
    venue: 'Islamic Center',
    venueAddress: '456 Park Avenue, East Side, City 12346',
    capacity: 50,
    attendeeCount: 35,
    status: 'approved',
    description: 'Learn the fundamentals of Hadith authentication, chains of narration, and the science of Rijal with renowned scholar.',
    hostName: 'Dr. Fatima Hassan',
    hostId: 'host2',
    hostRating: 5.0,
    hostVerified: true,
    agenda: [
      { title: 'Introduction to Hadith Sciences', arabicTitle: 'مقدمة في علوم الحديث', duration: 45 },
      { title: 'Authentication Methods', arabicTitle: 'طرق التوثيق', duration: 60 },
      { title: 'Practical Examples', arabicTitle: 'أمثلة عملية', duration: 45 },
      { title: 'Group Discussion', arabicTitle: 'نقاش جماعي', duration: 30 },
    ],
    venueFeatures: {
      qiblaDirection: true,
      prayerSpace: true,
      wuduFacilities: true,
      parking: true,
      wheelchairAccessible: false,
    },
    registeredCount: 35,
    checkedInCount: 32,
  },
  {
    id: '3',
    name: 'Youth Islamic Leadership',
    category: 'youth',
    date: '2025-01-20',
    startTime: '5:00 PM',
    endTime: '7:00 PM',
    venue: 'Community Hall',
    venueAddress: '789 Youth Street, North District, City 12347',
    capacity: 40,
    attendeeCount: 38,
    status: 'approved',
    description: 'Empowering the next generation of Muslim leaders through Islamic principles, character development, and community service.',
    hostName: 'Ustadh Ibrahim Khan',
    hostId: 'host3',
    hostRating: 4.8,
    hostVerified: true,
    agenda: [
      { title: 'Leadership in Islam', arabicTitle: 'القيادة في الإسلام', duration: 40 },
      { title: 'Character Building', arabicTitle: 'بناء الشخصية', duration: 40 },
      { title: 'Community Service Projects', arabicTitle: 'مشاريع خدمة المجتمع', duration: 40 },
    ],
    venueFeatures: {
      qiblaDirection: true,
      prayerSpace: false,
      wuduFacilities: false,
      parking: true,
      wheelchairAccessible: true,
    },
    registeredCount: 38,
    checkedInCount: 36,
  },
  {
    id: '4',
    name: 'Family Night Gathering',
    category: 'family',
    date: '2025-01-22',
    startTime: '6:00 PM',
    endTime: '9:00 PM',
    venue: 'Masjid Gardens',
    venueAddress: '321 Garden Lane, West End, City 12348',
    capacity: 100,
    attendeeCount: 75,
    status: 'approved',
    description: 'A beautiful evening for families to connect, share meals, enjoy activities, and strengthen community bonds in a halal environment.',
    hostName: 'Sister Aisha Rahman',
    hostId: 'host4',
    hostRating: 4.7,
    hostVerified: true,
    agenda: [
      { title: 'Welcome & Maghrib Prayer', arabicTitle: 'الترحيب وصلاة المغرب', duration: 30 },
      { title: 'Community Dinner', arabicTitle: 'عشاء جماعي', duration: 60 },
      { title: 'Family Activities', arabicTitle: 'أنشطة عائلية', duration: 60 },
      { title: 'Closing Remarks', arabicTitle: 'كلمات ختامية', duration: 30 },
    ],
    venueFeatures: {
      qiblaDirection: true,
      prayerSpace: true,
      wuduFacilities: true,
      parking: true,
      wheelchairAccessible: true,
    },
    registeredCount: 75,
    checkedInCount: 70,
  },
  {
    id: '5',
    name: 'Charity Fundraiser Dinner',
    category: 'charity',
    date: '2025-01-25',
    startTime: '7:00 PM',
    endTime: '10:00 PM',
    venue: 'Grand Hall',
    venueAddress: '555 Charity Boulevard, Central, City 12349',
    capacity: 200,
    attendeeCount: 180,
    status: 'approved',
    description: 'Join us for an elegant fundraising dinner supporting orphans and widows in need. Your contribution makes a difference.',
    hostName: 'Br. Yusuf Ahmed',
    hostId: 'host5',
    hostRating: 4.9,
    hostVerified: true,
    agenda: [
      { title: 'Reception & Registration', arabicTitle: 'الاستقبال والتسجيل', duration: 30 },
      { title: 'Fundraising Presentation', arabicTitle: 'عرض جمع التبرعات', duration: 45 },
      { title: 'Dinner Service', arabicTitle: 'خدمة العشاء', duration: 60 },
      { title: 'Auction & Closing', arabicTitle: 'المزاد والختام', duration: 45 },
    ],
    venueFeatures: {
      qiblaDirection: true,
      prayerSpace: true,
      wuduFacilities: true,
      parking: true,
      wheelchairAccessible: true,
    },
    registeredCount: 180,
    checkedInCount: 175,
  },
  {
    id: '6',
    name: 'Dawah Training Workshop',
    category: 'dawah',
    date: '2025-01-28',
    startTime: '9:00 AM',
    endTime: '12:00 PM',
    venue: 'Conference Room A',
    venueAddress: '888 Outreach Center, South End, City 12350',
    capacity: 25,
    attendeeCount: 20,
    status: 'approved',
    description: 'Learn effective dawah strategies, communication techniques, and how to share Islam with wisdom and beautiful preaching.',
    hostName: 'Sheikh Omar Suleiman',
    hostId: 'host6',
    hostRating: 5.0,
    hostVerified: true,
    agenda: [
      { title: 'Dawah Principles', arabicTitle: 'مبادئ الدعوة', duration: 60 },
      { title: 'Communication Skills', arabicTitle: 'مهارات التواصل', duration: 60 },
      { title: 'Role Play Exercises', arabicTitle: 'تمارين لعب الأدوار', duration: 60 },
    ],
    venueFeatures: {
      qiblaDirection: true,
      prayerSpace: true,
      wuduFacilities: true,
      parking: false,
      wheelchairAccessible: true,
    },
    registeredCount: 20,
    checkedInCount: 19,
  },
  {
    id: '7',
    name: 'Seerah Lecture Series',
    category: 'lecture',
    date: '2025-02-01',
    startTime: '3:00 PM',
    endTime: '5:00 PM',
    venue: 'Main Prayer Hall',
    venueAddress: '999 Prophet Street, Heritage District, City 12351',
    capacity: 80,
    attendeeCount: 45,
    status: 'approved',
    description: 'Explore the life of Prophet Muhammad (peace be upon him) with detailed analysis of his character, challenges, and triumphs.',
    hostName: 'Dr. Yasir Qadhi',
    hostId: 'host7',
    hostRating: 4.9,
    hostVerified: true,
    agenda: [
      { title: 'Early Life of the Prophet', arabicTitle: 'حياة النبي المبكرة', duration: 50 },
      { title: 'The Meccan Period', arabicTitle: 'الفترة المكية', duration: 50 },
      { title: 'Q&A Session', arabicTitle: 'جلسة أسئلة وأجوبة', duration: 20 },
    ],
    venueFeatures: {
      qiblaDirection: true,
      prayerSpace: true,
      wuduFacilities: true,
      parking: true,
      wheelchairAccessible: true,
    },
    registeredCount: 45,
    checkedInCount: 40,
  },
  {
    id: '8',
    name: 'Quran Memorization Program',
    category: 'education',
    date: '2025-02-05',
    startTime: '8:00 AM',
    endTime: '10:00 AM',
    venue: 'Study Room 3',
    venueAddress: '111 Learning Lane, Education Quarter, City 12352',
    capacity: 15,
    attendeeCount: 12,
    status: 'approved',
    description: 'Structured Quran memorization program with proven techniques, Tajweed practice, and personalized guidance for students.',
    hostName: 'Qari Muhammad Ali',
    hostId: 'host8',
    hostRating: 4.8,
    hostVerified: true,
    agenda: [
      { title: 'Tajweed Practice', arabicTitle: 'ممارسة التجويد', duration: 40 },
      { title: 'Memorization Session', arabicTitle: 'جلسة الحفظ', duration: 50 },
      { title: 'Review & Correction', arabicTitle: 'المراجعة والتصحيح', duration: 30 },
    ],
    venueFeatures: {
      qiblaDirection: true,
      prayerSpace: false,
      wuduFacilities: true,
      parking: false,
      wheelchairAccessible: false,
    },
    registeredCount: 12,
    checkedInCount: 12,
  },
];

export const myUpcomingEvents: HalaqahEvent[] = [mockEvents[0], mockEvents[1], mockEvents[2]];
export const myPastEvents: HalaqahEvent[] = [mockEvents[6], mockEvents[7]];
export const myCancelledEvents: HalaqahEvent[] = [
  {
    ...mockEvents[3],
    status: 'cancelled',
    cancellationReason: 'Venue unavailable due to maintenance',
  },
];

export const hostDashboardEvents: HalaqahEvent[] = mockEvents.slice(0, 5);
