/**
 * pageCatalog.ts — every user-navigable destination in the app.
 *
 * Source of truth for the deterministic nav matcher. Routes mirror
 * `src/app/router.tsx`. `aliases` are full natural phrases a user might type;
 * `keywords` are individual tokens (already lowercase). When adding a route to
 * the router, add it here too.
 */

export interface PageEntry {
  route: string;
  label: string;
  group: string;
  /** Individual tokens that hint at this page. */
  keywords: string[];
  /** Full natural phrases that should resolve directly to this page. */
  aliases: string[];
}

export const PAGE_CATALOG: PageEntry[] = [
  // ── Core / Raya ───────────────────────────────────────────────
  { route: '/', label: 'Home', group: 'Core',
    keywords: ['home', 'gateway', 'start', 'main', 'raya'], aliases: ['home', 'gateway', 'home page', 'take me home'] },
  { route: '/dashboard', label: 'Dashboard', group: 'Core',
    keywords: ['dashboard', 'widgets', 'overview', 'panel'], aliases: ['dashboard', 'my dashboard', 'take me to dashboard', 'open dashboard'] },
  { route: '/ai-assistant', label: 'Raya AI Assistant', group: 'Core',
    keywords: ['raya', 'assistant', 'chat', 'ai', 'companion'],
    aliases: ['raya', 'ai assistant', 'chat with raya', 'raya chat', 'assistant'] },
  { route: '/raya', label: 'Raya Hub', group: 'Core',
    keywords: ['raya', 'hub', 'whatsapp'], aliases: ['raya hub', 'raya on whatsapp'] },

  // ── Qur'an ────────────────────────────────────────────────────
  { route: '/quran', label: 'Qur’an', group: 'Qur’an',
    keywords: ['quran', 'mushaf', 'book'], aliases: ['quran', 'the quran', 'quran home', 'holy quran'] },
  { route: '/quran/read', label: 'Qur’an Reading', group: 'Qur’an',
    keywords: ['quran', 'read', 'reading', 'reader'], aliases: ['quran reading', 'read quran', 'quran reader'] },
  { route: '/quran/recitation', label: 'Qur’an Recitation', group: 'Qur’an',
    keywords: ['quran', 'recitation', 'recite', 'audio'], aliases: ['quran recitation', 'recite quran'] },
  { route: '/quran/recitation/diary', label: 'Recitation Diary', group: 'Qur’an',
    keywords: ['recitation', 'diary', 'log'], aliases: ['recitation diary'] },
  { route: '/quran/streak', label: 'Qur’an Streak', group: 'Qur’an',
    keywords: ['quran', 'streak'], aliases: ['quran streak', 'reading streak'] },
  { route: '/quran/bookmarks', label: 'Qur’an Bookmarks', group: 'Qur’an',
    keywords: ['quran', 'bookmarks', 'saved'], aliases: ['quran bookmarks', 'saved ayahs'] },
  { route: '/quran/hifz', label: 'Hifz', group: 'Qur’an',
    keywords: ['hifz', 'memorize', 'memorization'], aliases: ['hifz', 'memorize quran', 'quran memorization'] },
  { route: '/quran/hifz/memorize', label: 'Memorize', group: 'Qur’an',
    keywords: ['hifz', 'memorize'], aliases: ['memorize', 'hifz memorize'] },
  { route: '/quran/hifz/test', label: 'Hifz Test', group: 'Qur’an',
    keywords: ['hifz', 'test', 'quiz'], aliases: ['hifz test', 'memorization test'] },
  { route: '/quran/hifz/progress', label: 'Hifz Progress', group: 'Qur’an',
    keywords: ['hifz', 'progress'], aliases: ['hifz progress'] },
  { route: '/quran/hifz/circles', label: 'Hifz Circles', group: 'Qur’an',
    keywords: ['hifz', 'circles', 'group'], aliases: ['hifz circles', 'memorization circles'] },
  { route: '/quran/mushaf', label: 'Mushaf', group: 'Qur’an',
    keywords: ['mushaf', 'page', 'quran'], aliases: ['mushaf', 'mushaf view'] },
  { route: '/quran/search', label: 'Qur’an Concept Search', group: 'Qur’an',
    keywords: ['quran', 'search', 'concept'], aliases: ['quran search', 'concept search'] },
  { route: '/quran/research', label: 'Qur’an Research', group: 'Qur’an',
    keywords: ['quran', 'research', 'tafsir'], aliases: ['quran research', 'tafsir'] },
  { route: '/quran/tracks', label: 'Learning Tracks', group: 'Qur’an',
    keywords: ['quran', 'tracks', 'learning', 'course'], aliases: ['learning tracks', 'quran tracks'] },
  { route: '/quran/daily-ayah', label: 'Daily Ayah', group: 'Qur’an',
    keywords: ['daily', 'ayah', 'verse'], aliases: ['daily ayah', 'verse of the day'] },
  { route: '/quran/guess-ayah', label: 'Guess the Ayah', group: 'Qur’an',
    keywords: ['guess', 'ayah', 'game'], aliases: ['guess the ayah', 'guess ayah'] },
  { route: '/quran/tajweed-practice', label: 'Tajweed Practice', group: 'Qur’an',
    keywords: ['tajweed', 'practice'], aliases: ['tajweed practice', 'tajweed'] },
  { route: '/quran/workspace', label: 'Qur’an Workspace', group: 'Qur’an',
    keywords: ['quran', 'workspace', 'notes'], aliases: ['quran workspace', 'my notes'] },

  // ── Wealth / EIM / Finance ──────────────────────────────────
  { route: '/eim', label: 'EIM', group: 'Wealth',
    keywords: ['eim', 'wealth', 'invest', 'portfolio', 'mentor'],
    aliases: ['eim', 'wealth', 'my wealth', 'ethical investment mentor', 'investment mentor'] },
  { route: '/eim/library', label: 'EIM Library', group: 'Wealth',
    keywords: ['eim', 'library', 'lessons'], aliases: ['eim library', 'investing library'] },
  { route: '/eim/simulator', label: 'EIM Simulator', group: 'Wealth',
    keywords: ['simulator', 'eim', 'practice'], aliases: ['eim simulator', 'trading simulator'] },
  { route: '/eim/time-machine', label: 'EIM Time Machine', group: 'Wealth',
    keywords: ['time', 'machine', 'backtest'], aliases: ['time machine', 'eim time machine'] },
  { route: '/eim/strategy-comparator', label: 'Strategy Comparator', group: 'Wealth',
    keywords: ['strategy', 'comparator', 'compare'], aliases: ['strategy comparator', 'compare strategies'] },
  { route: '/eim/scenario-lab', label: 'Scenario Lab', group: 'Wealth',
    keywords: ['scenario', 'lab'], aliases: ['scenario lab'] },
  { route: '/eim/projection', label: 'Projection', group: 'Wealth',
    keywords: ['projection', 'forecast'], aliases: ['projection', 'wealth projection'] },
  { route: '/eim/mentor', label: 'EIM Mentor', group: 'Wealth',
    keywords: ['mentor', 'eim', 'coach'], aliases: ['eim mentor', 'investment mentor'] },
  { route: '/eim/analysis', label: 'EIM Analysis', group: 'Wealth',
    keywords: ['analysis', 'analyse'], aliases: ['eim analysis', 'portfolio analysis'] },
  { route: '/eim/candlesticks', label: 'Candlesticks', group: 'Wealth',
    keywords: ['candlesticks', 'candles', 'charts'], aliases: ['candlesticks', 'candlestick patterns'] },
  { route: '/eim/pattern-lab', label: 'Pattern Lab', group: 'Wealth',
    keywords: ['pattern', 'lab'], aliases: ['pattern lab'] },
  { route: '/eim/scholar-faqs', label: 'Scholar FAQs', group: 'Wealth',
    keywords: ['scholar', 'faqs', 'fatwa'], aliases: ['scholar faqs', 'eim scholar faqs'] },
  { route: '/eim/ulama', label: 'Ulama', group: 'Wealth',
    keywords: ['ulama', 'scholars'], aliases: ['ulama', 'scholars'] },
  { route: '/eim/mirror', label: 'EIM Mirror', group: 'Wealth',
    keywords: ['mirror', 'eim', 'statement'], aliases: ['eim mirror', 'portfolio mirror'] },
  { route: '/screener', label: 'Shariah Stock Screener', group: 'Wealth',
    keywords: ['screener', 'shariah', 'stock', 'halal'],
    aliases: ['screener', 'stock screener', 'shariah screener', 'is this stock halal', 'halal stocks'] },
  { route: '/zakat', label: 'Zakat Calculator', group: 'Wealth',
    keywords: ['zakat', 'calculator', 'charity'], aliases: ['zakat', 'zakat calculator', 'calculate zakat'] },
  { route: '/purification', label: 'Purification Calculator', group: 'Wealth',
    keywords: ['purification', 'purify', 'cleanse'], aliases: ['purification', 'purification calculator', 'purify income'] },
  { route: '/wallet', label: 'Wallet', group: 'Wealth',
    keywords: ['wallet', 'dnz', 'balance', 'tokens'], aliases: ['wallet', 'my wallet', 'dnz wallet', 'my balance'] },
  { route: '/islamic-banking', label: 'Islamic Banking', group: 'Wealth',
    keywords: ['islamic', 'banking', 'bank'], aliases: ['islamic banking', 'bank'] },
  { route: '/debt', label: 'Debt Restructuring', group: 'Wealth',
    keywords: ['debt', 'loan', 'restructuring'], aliases: ['debt', 'debt restructuring'] },
  { route: '/bait-ul-maal', label: 'Bait-ul-Maal', group: 'Wealth',
    keywords: ['baitulmaal', 'charity', 'sadaqah', 'donate'], aliases: ['bait ul maal', 'baitulmaal', 'charity fund'] },

  // ── Gratitude / Faith practice ────────────────────────────────
  { route: '/barakah-labs', label: 'Barakah Labs', group: 'Practice',
    keywords: ['barakah', 'baraka', 'gratitude', 'shukr', 'labs', 'reflection'],
    aliases: ['barakah labs', 'baraka', 'gratitude', 'barakah'] },
  { route: '/prayer-times', label: 'Prayer Times', group: 'Practice',
    keywords: ['prayer', 'salah', 'times', 'namaz', 'adhan'], aliases: ['prayer times', 'salah times', 'namaz times'] },
  { route: '/qibla', label: 'Qibla Compass', group: 'Practice',
    keywords: ['qibla', 'compass', 'direction'], aliases: ['qibla', 'qibla compass', 'qibla direction'] },
  { route: '/calendar', label: 'Hijri Calendar', group: 'Practice',
    keywords: ['calendar', 'hijri', 'islamic', 'date'], aliases: ['calendar', 'hijri calendar', 'islamic calendar'] },
  { route: '/faith', label: 'Faith', group: 'Practice',
    keywords: ['faith', 'deen', 'iman'], aliases: ['faith', 'faith home'] },
  { route: '/faith/masjid-finder', label: 'Masjid Finder', group: 'Practice',
    keywords: ['masjid', 'mosque', 'finder', 'nearby'], aliases: ['masjid finder', 'find a mosque', 'nearby masjid'] },
  { route: '/ramadan-kids', label: 'Ramadan for Kids', group: 'Practice',
    keywords: ['ramadan', 'kids', 'children'], aliases: ['ramadan kids', 'ramadan for kids'] },

  // ── Community ─────────────────────────────────────────────────
  { route: '/halaqah', label: 'Halaqah', group: 'Community',
    keywords: ['halaqah', 'circle', 'gathering', 'community'], aliases: ['halaqah', 'circles', 'study circle'] },
  { route: '/events', label: 'Events', group: 'Community',
    keywords: ['events', 'event', 'meetup'], aliases: ['events', 'upcoming events'] },
  { route: '/connections', label: 'Connections', group: 'Community',
    keywords: ['connections', 'network', 'contacts', 'people'], aliases: ['connections', 'networking', 'my network'] },
  { route: '/messages', label: 'Messages', group: 'Community',
    keywords: ['messages', 'dm', 'inbox', 'conversations'], aliases: ['messages', 'my messages', 'inbox', 'dms'] },
  { route: '/media', label: 'Media', group: 'Community',
    keywords: ['media', 'videos', 'content'], aliases: ['media', 'media library'] },

  // ── Marketplace / Commerce ────────────────────────────────────
  { route: '/souk', label: 'Souk', group: 'Marketplace',
    keywords: ['souk', 'marketplace', 'shop', 'store', 'market', 'buy'],
    aliases: ['souk', 'marketplace', 'the souk', 'shop', 'store'] },
  { route: '/souk/create', label: 'Create Listing', group: 'Marketplace',
    keywords: ['create', 'listing', 'sell'], aliases: ['create listing', 'sell something', 'new listing'] },
  { route: '/souk/saved', label: 'Saved Listings', group: 'Marketplace',
    keywords: ['saved', 'listings', 'favourites'], aliases: ['saved listings', 'my saved items'] },
  { route: '/souk/my-listings', label: 'My Listings', group: 'Marketplace',
    keywords: ['my', 'listings'], aliases: ['my listings'] },
  { route: '/commerce', label: 'Commerce', group: 'Marketplace',
    keywords: ['commerce', 'business', 'trade'], aliases: ['commerce', 'business hub'] },
  { route: '/real-estate', label: 'Real Estate', group: 'Marketplace',
    keywords: ['real', 'estate', 'property', 'house'], aliases: ['real estate', 'property'] },

  // ── Life / Services ───────────────────────────────────────────
  { route: '/matrimony', label: 'Matrimony', group: 'Life',
    keywords: ['matrimony', 'marriage', 'sakinah', 'nikah', 'spouse'],
    aliases: ['matrimony', 'sakinah', 'marriage', 'find a spouse'] },
  { route: '/education', label: 'Education', group: 'Life',
    keywords: ['education', 'learn', 'courses', 'school'], aliases: ['education', 'learning'] },
  { route: '/chamber', label: 'Chamber', group: 'Life',
    keywords: ['chamber', 'business', 'ventures'], aliases: ['chamber', 'business chamber'] },
  { route: '/shark-tank', label: 'Shark Tank', group: 'Life',
    keywords: ['shark', 'tank', 'ventures', 'investors', 'startup'], aliases: ['shark tank', 'ventures', 'pitch'] },
  { route: '/digital-id', label: 'Digital ID', group: 'Life',
    keywords: ['digital', 'id', 'identity'], aliases: ['digital id', 'digital identity'] },
  { route: '/research', label: 'Research', group: 'Life',
    keywords: ['research', 'articles', 'scholars'], aliases: ['research', 'research home'] },
  { route: '/voice-companion', label: 'Voice Companion', group: 'Life',
    keywords: ['voice', 'companion', 'speak'], aliases: ['voice companion', 'voice mode'] },

  // ── Account / Settings ────────────────────────────────────────
  { route: '/profile', label: 'Profile', group: 'Account',
    keywords: ['profile', 'account', 'me'], aliases: ['profile', 'my profile', 'account'] },
  { route: '/settings', label: 'Settings', group: 'Account',
    keywords: ['settings', 'preferences', 'options'], aliases: ['settings', 'preferences', 'app settings'] },
  { route: '/settings/notifications', label: 'Notification Settings', group: 'Account',
    keywords: ['notification', 'settings', 'alerts'], aliases: ['notification settings'] },
  { route: '/settings/whatsapp', label: 'WhatsApp Link', group: 'Account',
    keywords: ['whatsapp', 'link', 'connect'], aliases: ['link whatsapp', 'whatsapp settings'] },
  { route: '/notifications', label: 'Notifications', group: 'Account',
    keywords: ['notifications', 'alerts', 'bell'], aliases: ['notifications', 'my notifications'] },
  { route: '/deep-kyc', label: 'Identity Verification', group: 'Account',
    keywords: ['kyc', 'verify', 'identity', 'verification'], aliases: ['kyc', 'verify identity', 'deep kyc', 'identity verification'] },
  { route: '/support', label: 'Support', group: 'Account',
    keywords: ['support', 'contact'], aliases: ['support', 'contact support'] },
  { route: '/help', label: 'Help & Support', group: 'Account',
    keywords: ['help', 'faq', 'support'], aliases: ['help', 'help and support'] },
  { route: '/feedback', label: 'Feedback', group: 'Account',
    keywords: ['feedback', 'suggestion', 'report'], aliases: ['feedback', 'give feedback', 'share feedback'] },
  { route: '/about', label: 'About', group: 'Account',
    keywords: ['about', 'info'], aliases: ['about', 'about zaryah'] },
];
